# Generated by Django 4.1 on 2022-08-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publishedOn',
            field=models.DateField(blank=True, null=True),
        ),
    ]
