# Generated by Django 4.1 on 2022-08-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_blog_publishedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('review', models.CharField(max_length=100)),
            ],
        ),
    ]
